# File: app.py
from flask import Flask, render_template

# --- Configuration: Dork Arsenal ---
# Paste your full GOOGLE_DORKS and GITHUB_DORKS dictionaries here
GOOGLE_DORKS = {
    "🗂️ Config & Env Files": [
        {"dork": 'ext:xml | ext:conf | ext:cnf | ext:reg | ext:inf | ext:rdp | ext:cfg | ext:txt | ext:ora | ext:ini | ext:env', "desc": "Finds a wide range of config files"},
        {"dork": 'inurl:/.env "DB_PASSWORD"', "desc": "Exposed environment files with DB credentials"},
        {"dork": 'filetype:config "username" "password"', "desc": "Config files containing credentials"},
        {"dork": 'intext:"Environment" intext:"DATABASE_URL"', "desc": "Finds pages exposing database URLs"},
        {"dork": 'filetype:yml or filetype:yaml', "desc": "Finds YAML configuration files"},
        {"dork": 'filetype:json api.keys', "desc": "JSON files containing API keys"},
        {"dork": 'inurl:web.config "connectionString"', "desc": "ASP.NET config with DB connection strings"},
    ],
    "🗄️ Database Dumps": [
        {"dork": 'ext:sql | ext:dbf | ext:mdb', "desc": "Finds various database file types"},
        {"dork": 'filetype:sql "sql dump" "password"', "desc": "Database dumps containing passwords"},
        {"dork": '"index of" "database.sql"', "desc": "Directory listings of SQL databases"},
        {"dork": 'intext:"-- MySQL dump" filetype:sql', "desc": "Finds files generated by mysqldump"},
        {"dork": '"index of" "dump.sql.gz"', "desc": "Compressed SQL database dumps"},
    ],
    "📜 Log Files": [
        {"dork": 'ext:log', "desc": "Finds all files with the .log extension"},
        {"dork": 'filetype:log "password"', "desc": "Log files containing the word 'password'"},
        {"dork": 'inurl:"/logs/" "access.log"', "desc": "Exposed access logs"},
        {"dork": 'allintext:username filetype:log', "desc": "Log files containing usernames"},
        {"dork": 'filetype:log "API key"', "desc": "Log files containing API keys"},
        {"dork": 'filetype:log "Failed password for"', "desc": "Logs showing failed login attempts"},
    ],
    "📦 Backups & Old Files": [
        {"dork": 'ext:bkf | ext:bkp | ext:bak | ext:old | ext:backup', "desc": "Common backup file extensions"},
        {"dork": '"index of" "backup.zip"', "desc": "Directory listing of backup.zip"},
        {"dork": 'filetype:tar.gz "password"', "desc": "Compressed backups containing passwords"},
        {"dork": '"Index of" "site.zip"', "desc": "Full site backups in zip format"},
    ],
    "📄 Exposed Documents & Keys": [
        {"dork": 'ext:doc | ext:docx | ext:odt | ext:pdf | ext:rtf | ext:sxw | ext:psw | ext:ppt | ext:pptx | ext:pps | ext:csv | ext:xls | ext:xlsx', "desc": "Various document types"},
        {"dork": 'filetype:xls "username" "password"', "desc": "Spreadsheets with credentials"},
        {"dork": 'filetype:pem "PRIVATE KEY"', "desc": "Exposed PEM private keys"},
        {"dork": 'filetype:ppk "Private-Lines"', "desc": "Exposed PuTTY private keys"},
        {"dork": 'filetype:kdb "KeePass"', "desc": "KeePass password database files"},
    ],
    "📂 Directory Listings": [
        {"dork": 'intitle:"index of"', "desc": "Finds servers with directory listing enabled"},
        {"dork": 'intitle:"index of" "private"', "desc": "Directory listings of 'private' folders"},
        {"dork": 'intitle:"index of" "/.ssh/"', "desc": "Exposed SSH key directories"},
        {"dork": 'intitle:"index of" "/.aws/"', "desc": "Exposed AWS credential directories"},
        {"dork": 'intitle:"index of" "wp-admin"', "desc": "Exposed WordPress admin directories"},
    ],
    "💉 SQL Injection": [
        {"dork": 'inurl:.php?id=', "desc": "Potential SQLi in PHP id parameter"},
        {"dork": 'inurl:.asp?id=', "desc": "Potential SQLi in ASP id parameter"},
        {"dork": 'intext:"sql syntax near"', "desc": "Pages displaying SQL syntax errors"},
        {"dork": '"unclosed quotation mark after the character string"', "desc": "SQL error message disclosures"},
    ],
    "🔓 Exposed Login Pages": [
        {"dork": 'intitle:"login" | intitle:"signin"', "desc": "Generic login/signin pages"},
        {"dork": 'intitle:"admin login"', "desc": "Finds admin login pages specifically"},
        {"dork": 'intitle:"cPanel"', "desc": "cPanel web hosting login"},
        {"dork": 'intitle:"phpMyAdmin" inurl:"setup.php"', "desc": "phpMyAdmin setup pages"},
    ],
    "🖥️ 3rd Party Services": [
        {"dork": 'intitle:"Jenkins" "Dashboard"', "desc": "Exposed Jenkins dashboards"},
        {"dork": 'inurl:"/grafana/dashboard/"', "desc": "Exposed Grafana dashboards"},
        {"dork": 'intitle:"Jira" "Log in"', "desc": "Jira login pages"},
        {"dork": 'intitle:"phpinfo()"', "desc": "Exposed phpinfo pages"},
    ]
}

GITHUB_DORKS = {
    "🔑 API Keys & Tokens": [
        {"dork": '"api_key"', "desc": "Generic API keys"},
        {"dork": '"authorization_bearer"', "desc": "Bearer tokens for API authentication"},
        {"dork": '"xoxp-" OR "xoxb-"', "desc": "Slack API tokens"},
        {"dork": 'AKIA[0-9A-Z]{16}', "desc": "AWS Access Key IDs (regex)"},
        {"dork": 'shodan_api_key', "desc": "Shodan API keys"},
        {"dork": 'ghp_[0-9a-zA-Z]{36}', "desc": "GitHub personal access tokens"},
        {"dork": '"AIzaSy"', "desc": "Google API keys"},
    ],
    "🔏 Private Keys": [
        {"dork": '"-----BEGIN OPENSSH PRIVATE KEY-----"', "desc": "OpenSSH private keys"},
        {"dork": '"-----BEGIN RSA PRIVATE KEY-----"', "desc": "RSA private keys"},
        {"dork": '"-----BEGIN EC PRIVATE KEY-----"', "desc": "Elliptic Curve private keys"},
        {"dork": 'extension:pem private', "desc": "Private key files with .pem extension"},
        {"dork": 'extension:ppk', "desc": "PuTTY private key files"},
    ],
    "📜 Config Files & Credentials": [
        {"dork": 'filename:.env', "desc": "Environment configuration files"},
        {"dork": 'filename:secrets.yml', "desc": "Ruby on Rails secrets files"},
        {"dork": 'filename:database.yml', "desc": "Database configuration files"},
        {"dork": 'filename:settings.py "SECRET_KEY"', "desc": "Django secret keys"},
        {"dork": 'filename:wp-config.php', "desc": "WordPress config files"},
        {"dork": 'filename:.npmrc _auth', "desc": "NPM authentication tokens"},
        {"dork": 'filename:sftp-config.json', "desc": "SFTP connection settings"},
        {"dork": 'filename:.netrc password', "desc": ".netrc files with passwords"},
    ],
    "🔐 Passwords & Secrets": [
        {"dork": '"DB_PASSWORD"', "desc": "Database passwords in environment variables"},
        {"dork": '"jdbc:mysql" password', "desc": "JDBC connection strings with passwords"},
        {"dork": 'language:sql "password"', "desc": "Passwords in SQL files"},
        {"dork": 'language:yaml "password"', "desc": "Passwords in YAML files"},
        {"dork": '"client_secret"', "desc": "OAuth client secrets"},
        {"dork": 'send_keys "password"', "desc": "Passwords being sent in automation scripts"},
    ],
    "📁 Sensitive Filenames": [
        {"dork": 'filename:id_rsa', "desc": "Private SSH keys"},
        {"dork": 'filename:bash_history', "desc": "Command line history"},
        {"dork": 'filename:zsh_history', "desc": "Zsh shell history"},
        {"dork": 'filename:credentials .aws', "desc": "AWS credentials file"},
        {"dork": 'path:.git/config', "desc": "Git configuration files with remotes"},
    ],
    "💻 Vulnerable Code Patterns": [
        {"dork": 'language:php "eval($_GET"', "desc": "PHP code execution from GET parameter"},
        {"dork": 'language:python "pickle.loads"', "desc": "Potential RCE in Python via pickle"},
        {"dork": 'language:js "dangerouslySetInnerHTML"', "desc": "React code susceptible to XSS"},
        {"dork": 'language:java "setHostnameVerifier"', "desc": "Java code with disabled hostname verification"},
        {"dork": '"strcpy" language:c', "desc": "Unsafe C function prone to buffer overflows"},
    ]
}

app = Flask(__name__)

@app.route('/')
def home():
    return render_template(
        'index.html',
        google_dorks=GOOGLE_DORKS,
        github_dorks=GITHUB_DORKS
    )

if __name__ == '__main__':
    # This part is for local testing only. The server will use gunicorn.
    app.run(debug=True)
